n = input('Digite qualquer coisa: ')
a = n.isspace()
b = n.isnumeric()
c = n.isalpha()
d = n.isalnum()
e = n.isupper()
f = n.islower()

print('O tipo primitivo desse valor é ',type(n))
print('Só tem espaços? {}'.format(a))
print('É um número? {}'.format(b))
print('É alfabético? {}'.format(c))
print('É alfanumérico? {}'.format(d))
print('Está em maiúsculas? {}'.format(e))
print('Está em minúsculas? {}'.format(f))
